name: di-gradle-sam

on:
  push:
    branches:
      - 'main'
    paths:
      - 'gradle-sam/*'
      - '.github/workflows/build_gradle_sam.yml'
  registry_package:
    types:
      - 'updated'

  workflow_dispatch:
    inputs:
      image_tag:
        description: "Tag used within docker repository to mark as unique"
        required: false
        type: string

jobs:
  build-and-push:
    if: github.event.type != 'package' || github.event.registry_package.package.name == 'aws-sam'
    uses: alphagov/di-dockerfiles/.github/workflows/publish_to_ghcr.yml@main
    permissions:
      contents: read
      packages: write
    with:
      docker_context: ./gradle-sam
      push_to_ghcr: true
      ghcr_repo: ghcr.io/alphagov/gradle-sam
      image_tag: ${{ github.event.inputs.image_tag }}

